// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/pfsense/openvpn/connections": {
            "get": {
                "description": "Retrieves information about all OpenVPN connections",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PFSENSE"
                ],
                "summary": "Get all OpenVPN connections",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/pfsense.PfsenseOpenVPNConnection"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/pve/reset": {
            "get": {
                "description": "Retrieves the timestamp of the last lab reset",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PVE"
                ],
                "summary": "Get last reset time",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Resets all VMs to their latest snapshots",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PVE"
                ],
                "summary": "Reset the lab",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/pve/vms": {
            "get": {
                "description": "Retrieves information about all virtual machines",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PVE"
                ],
                "summary": "Get all VMs",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/proxmox.VMInfo"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/pve/vms/reset": {
            "post": {
                "description": "Resets all virtual machines",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PVE"
                ],
                "summary": "Reset all VMs",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/proxmox.VMOperationResult"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/pve/vms/start": {
            "post": {
                "description": "Starts all virtual machines",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PVE"
                ],
                "summary": "Start all VMs",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/proxmox.VMOperationResult"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/pve/vms/stop": {
            "post": {
                "description": "Stops all virtual machines",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PVE"
                ],
                "summary": "Stop all VMs",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/proxmox.VMOperationResult"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "pfsense.PfsenseOpenVPNConnection": {
            "type": "object",
            "properties": {
                "common_name": {
                    "type": "string"
                },
                "connect_time_unix": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "proxmox.VMInfo": {
            "type": "object",
            "properties": {
                "cpu": {
                    "description": "当前 CPU 使用率",
                    "type": "number"
                },
                "cpus": {
                    "description": "最大可用 CPU 数量",
                    "type": "number"
                },
                "disk": {
                    "description": "当前磁盘使用率",
                    "type": "number"
                },
                "diskread": {
                    "description": "总磁盘读取量 (字节)",
                    "type": "integer"
                },
                "diskwrite": {
                    "description": "总磁盘写入量 (字节)",
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "maxdisk": {
                    "description": "根磁盘大小 (字节)",
                    "type": "integer"
                },
                "maxmem": {
                    "description": "最大内存 (字节)",
                    "type": "integer"
                },
                "mem": {
                    "description": "当前内存使用",
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "netin": {
                    "description": "总网络流入量 (字节)",
                    "type": "integer"
                },
                "netout": {
                    "description": "总网络流出量 (字节)",
                    "type": "integer"
                },
                "node": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "uptime": {
                    "description": "运行时间 (秒)",
                    "type": "integer"
                }
            }
        },
        "proxmox.VMOperationResult": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "vmid": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "GOAD Dashboard API",
	Description:      "GOAD Dashboard API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
