definitions:
  pfsense.PfsenseOpenVPNConnection:
    properties:
      common_name:
        type: string
      connect_time_unix:
        type: integer
      id:
        type: integer
    type: object
  proxmox.VMInfo:
    properties:
      cpu:
        description: 当前 CPU 使用率
        type: number
      cpus:
        description: 最大可用 CPU 数量
        type: number
      disk:
        description: 当前磁盘使用率
        type: number
      diskread:
        description: 总磁盘读取量 (字节)
        type: integer
      diskwrite:
        description: 总磁盘写入量 (字节)
        type: integer
      id:
        type: string
      maxdisk:
        description: 根磁盘大小 (字节)
        type: integer
      maxmem:
        description: 最大内存 (字节)
        type: integer
      mem:
        description: 当前内存使用
        type: number
      name:
        type: string
      netin:
        description: 总网络流入量 (字节)
        type: integer
      netout:
        description: 总网络流出量 (字节)
        type: integer
      node:
        type: string
      status:
        type: string
      uptime:
        description: 运行时间 (秒)
        type: integer
    type: object
  proxmox.VMOperationResult:
    properties:
      message:
        type: string
      success:
        type: boolean
      vmid:
        type: string
    type: object
info:
  contact: {}
  description: GOAD Dashboard API
  title: GOAD Dashboard API
  version: "1.0"
paths:
  /api/pfsense/openvpn/connections:
    get:
      consumes:
      - application/json
      description: Retrieves information about all OpenVPN connections
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/pfsense.PfsenseOpenVPNConnection'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get all OpenVPN connections
      tags:
      - PFSENSE
  /api/pve/reset:
    get:
      consumes:
      - application/json
      description: Retrieves the timestamp of the last lab reset
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: integer
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get last reset time
      tags:
      - PVE
    post:
      consumes:
      - application/json
      description: Resets all VMs to their latest snapshots
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Reset the lab
      tags:
      - PVE
  /api/pve/vms:
    get:
      consumes:
      - application/json
      description: Retrieves information about all virtual machines
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/proxmox.VMInfo'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get all VMs
      tags:
      - PVE
  /api/pve/vms/reset:
    post:
      consumes:
      - application/json
      description: Resets all virtual machines
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/proxmox.VMOperationResult'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Reset all VMs
      tags:
      - PVE
  /api/pve/vms/start:
    post:
      consumes:
      - application/json
      description: Starts all virtual machines
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/proxmox.VMOperationResult'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Start all VMs
      tags:
      - PVE
  /api/pve/vms/stop:
    post:
      consumes:
      - application/json
      description: Stops all virtual machines
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/proxmox.VMOperationResult'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Stop all VMs
      tags:
      - PVE
swagger: "2.0"
